### ISSUE TITLE
DBの保存系

### ISSUE THREAD

**Issue by gomo** [SunriseDigital/cs-sdx#23]
保存系を実装する。
## PR

https://github.com/SunriseDigital/cs-sdx/pull/37

[旧PR](https://github.com/SunriseDigital/cs-sdx/pull/25)
## TODO
- [x] Fetch系をSelectに移動。
- [x] 独自Connectionクラスを作成。
- [x] Fetch系/Execute系メソッドをConnectionに移動。
- [x] Record.GetRecordSetのConnectionが大量に生成される問題をどうにかできないか？
- [x] Insertクラスの作成。Connectionに実行メソッド作成
- [x] Insertでカラムの値をサブクエリで更新する。
- [x] Updateクラスの作成。Connectionに実行メソッド作成。
- [x] UpdateのWhereはUpdateの対象テーブルで固定されているが、問題ないか検討。
- [x] Deleteクラスの作成。Connectionに実行メソッド作成。
- [x] Connection.DbConnectionを隠蔽できないか確認する。
- [x] Select.AdapterのSetterは隠蔽できないか検討する。
- [x] Record編集の実装。
- [x] Record新規保存の実装。
- [x] Record削除の実装。
- [x] Queryの名前空間名を変更する。Queryは「問い合わせ」なので。
- [x] インターフェースを変えたので、隠蔽できるプロパティ、メソッドがないかチェック
- [x] Update/Insert/DeleteもCloneに対応。
- [x] Select/Update/Insert/Deleteのコンストラクタをinternalに
- [x] Save/DeleteはConnectionに移動。

**Comment by gomo** [comment]
## 更新系メソッドの場所

Adapterクラスはまさにデータベースを表現したクラスです。各接続はAdapter.CreateConnection()で生成される`DbConnection`です。PHPのSDXと少し違う発想ですね。

Adapterには今のところ下記のような機能・責任があります。
- SelectやDbCommandとDbConnectionやDbTransactionを使ってDBに問い合わせをするFetch系メソッド。
- 各DBベンダー毎のSQLの方言を吸収する。

で、更新系メソッドはAdapterに作るのが直感的かと思います。

``` c#
var db = new Sdx.Db.SqlServerAdapter();
db.ConnectionString = "SomeConnectionString...";

using (var conn = db.CreateConnection())
{
  conn.Open();
  using (var transaction = conn.BeginTransaction())
  {
    db.Insert("shop", new Dictionary<string, string> {
      { "name", "FooBar" },
      { "area_id", "1"}
    });
  }
}
```

だとすると、レコードをつかって新規保存するコードはどうなるかというと

``` c#
var shop = new Test.Orm.Shop();
shop
  .Set("name", "FooBar")
  .Set("area_id", "1");

using (var conn = db.CreateConnection())
{
  conn.Open();
  using (var transaction = conn.BeginTransaction())
  {
    shop.Save(db, transaction);
  }
}
```

う〜ん・・・`shop.Save(db, transaction)`とAdapterとDbTransactionを渡してるのはなんでなんだ？という疑問がわかないだろうか？

こんなパターンも思いついた。

``` c#
var shop = new Test.Orm.Shop();
shop
  .Set("name", "FooBar")
  .Set("area_id", "1");

using (var conn = db.CreateConnection())
{
  conn.Open();
  using (var transaction = conn.BeginTransaction())
  {
    db.SaveRecord(shop, transaction);
  }
}
```

こちらの方がイメージしやすいコードな気はするし、Fetch系がAdapterにあるので、クライアントコードでAdapterが手に入る可能性は高いので、Adapterを手に入れるのが難しいことは無さそう。

ただ、気になるのは、ヘルパー系のショートカットメソッドを用意する時、AdapterとDbTransactionあるいはAdapterとDbConnectionを渡さないといけない確率は非常に高いと思う。

ベストなのは`conn.Adapter`で生成したAdapterにアクセスできれば全て解決する。Connectionをラッピングしたクラス、Sdx.Db.Connectionを作ったらどうだろうか？

``` c#
var shop = new Test.Orm.Shop();
shop
  .Set("name", "FooBar")
  .Set("area_id", "1");

using (var conn = db.CreateConnection())
{
  conn.Open();
  conn.BeginTransaction();
  shop.Save(conn);
  conn.Commit();
}
```

当然Sdx.Db.ConnectionはIDisposableを実装する必要がある。中にDbTransactionも保持し、Disposeで開放してやれば、問題なく解放できそうだ。また、これによりAdapterのFetch系メソッドも整理できそうだ。 :smile: 

ただ、ちょっと大変な変更なるかもしれないな。特にテストケース。でもやったほうが良さそうな変更ではある。

**Comment by gomo** [comment]
https://github.com/SunriseDigital/cs-sdx/issues/23#issuecomment-141411366

この件で連休中考えてたんですけど、[このコミット](https://github.com/SunriseDigital/cs-sdx/commit/02d4ceaf4d79b61a7cf5aae7af804ab44df499ba)でAdapter.CreateSelectをやめましたが、やっぱりそこに戻したほうがいいような気がしてきた。

``` c#
var creator = new Creator();
var product = creator.CreateProduct();
```

みたないな流れで`product.Creator`で`creator`にアクセスできるのって自然な気がするんですよね。でSelectは各DBベンダーの違いを吸収するためにどうしてもAdapterが必要なので内部にAdapterを持つ必要があるし、Adapterから生成されるのは自然な気がしました。

問題は、そのコミットメッセージにあるように、AdapterがFetch系を持っていること。なので、いっそのこと、Fetch系をSelectに移動しちゃったらどうだろうか？

``` c#
var select = db.CreateSelect();

select
   .AddFrom(new Test.Orm.Table.Shop())
   .AddOrder("id", Sdx.Db.Query.Order.ASC);
select.SetLimit(1);

var conn = db.CreateConnection();
var shops = select.FetchRecordSet<Test.Orm.Shop>(conn);
```

こんな感じになる。

**Comment by gomo** [comment]
## usingの途中でreturnすると？

https://github.com/SunriseDigital/cs-sdx/blob/dfecdb4f44e100d654eb99ad3421472650647355/Sdx/Db/Adapter.cs#L136

ちゃんとDisposeが呼ばれます。見た目的には気持ち悪いですね・・・仕組みを知れば納得です。

usingブロックはtry/finalyブロックに展開されます。

``` c#
MemoryStream ms = new MemoryStream();
try
{
    // code
    return 0;
}
finally
{
    ms.Dispose();
}
```

でfinallyはreturnした時に呼ばれるかどうかですが、finallyは結構しつこく呼ばれます。どんな時に呼ばれないかは[このサイト](http://dobon.net/vb/dotnet/beginner/tryfinally.html)が詳しいです。

**Comment by gomo** [comment]
## Disposeの実装について

もし自分で実装する時は↓をもう一度よく読みましょう。
http://ufcpp.net/study/csharp/rm_disposable.html

今回は

> 例えば、他の IDisposable オブジェクトをメンバーに持っていて、間接的にしか非管理リソースを使わない場合もあります。 

このパターンに相当します。この場合は

> 直接触れる部分はあくまでも .NET Framework の管理化にあるオブジェクトになります。

なので、デストラクタで触っていは行けないリソースになります。なので、今回はこのような実装になっています。

https://github.com/SunriseDigital/cs-sdx/blob/dfecdb4f44e100d654eb99ad3421472650647355/Sdx/Db/Connection.cs#L52-L76

**Comment by gomo** [comment]
## 各種メソッド場所で悩み中

Connectionクラスができたのでいろいろ悩ましくなってきた。

### 現状の整理

#### 場所

| メソッド | 場所 |
| :-- | :-- |
| Commandを使うFetch系メソッド | Adapter |
| Selectを使うFetch系メソッド | Select |
| 更新系メソッド | Connection |

微妙だけど理由は下記の通り。
- Selectを使うFetch系メソッドは（当たり前だが）Selectが必ず必要なので、引数に渡すより自分自身が持っていたほうがより。`select.FetchRecord()`というのはインターフェースの意味的にも問題ないと思われる。また、取得時のConnectionは中で生成してその場で破棄してしまえば問題ないので必須ではない。
- 更新系はトランザクションを必要とし、複数のレコードを一つのトランザクションで更新することはよくあるので、クライアントコードからConnectionを渡せるべきである。外部から渡すくらいなら、いっそConnectionが持ってればOKなのでは？
- Commandを使うFetch系メソッドはCommandに作るわけにはいかず、また、Selectにあるのも不自然である。Connectionに置くてもあるが、Connectionの使い捨てしたい時もあるのでAdapterに置いた。

#### 責任

##### Adapter

抽象クラスでSqlServer用・MySql用などが有り。DBそのものを表現したクラス。各DBベンダーの違いを吸収するのが主な役目。各種Create系メソッドを保持。Factory的な側面もある。Commandを受け取ってDBに問い合わせをする機能もある。

##### Connection

一回の接続を表したクラス。各DB用のものは無く具象クラスです。各DBベンダーごとの違いがあったらAdapterに吸収させる。一回のWEBリクエスト（Context）で複数回生成され、Disposeされる可能性がある（ContextにConnectionを保持させて使い回すことも検討中）。

##### Select

Select文を生成するクラス。Connection同様具象クラスでベンダーごとの違い吸収はAdapterに委譲している。Sdx.Db.Query名前空間に属する。

**Comment by gomo** [comment]
> 現状の整理

こうやって整理すると見えてきますね。

まず、Adapterクラスの責任が微妙な気がした。DBそのものを表したクラス、と考えるとFactory的な便利メソッドを集めておくのはまあ良しとして、Commendを使うFetch系があるのはSRPに違反する気がする。

意味的にはFetch系も更新系も全てConnectionにあるのが自然な気がしてきた。

> また、取得時のConnectionは中で生成してその場で破棄してしまえば問題ないので必須ではない。

というのも、知らない内に生成されて使い捨てられるより、クライアントが接続を把握するべきだとも思う。

SelectクラスはCommandを生成するクラス、という位置づけである。CommandはDisposeする必要があるので、直接ConnectionにSelectを渡せる便利メソッドはあったほうが良い。

更新系メソッドはConnectionに置いてもいいが、Update/InsertクラスをSdx.Db.Query名前空間に作るのも手だと思った。こいつらもあくまでCommadを生成するのがその責任である。で、それを受け取って実行するのはConnectionクラス。

作りながら、こっちにあったら便利だなー的な感じで場所を決めていくのは良くないと思った。あくまで、クラスの責任というのを明確にしながら作っていくのが良いと思う。

**Comment by gomo** [comment]
> Fetch系/Execute系メソッドをConnectionに移動。

https://github.com/SunriseDigital/cs-sdx/commit/1223138734717a416db0f6a52f954ea015d2ce2a
このコミットで実装した。

**Comment by gomo** [comment]
> Insertクラスの作成。Connectionに実行メソッド作成

https://github.com/SunriseDigital/cs-sdx/commit/4493ad3f26767c59cf4fdd07862b367487023616
このコミットで実装。

travisだけテストがコケてけっこう大変だった。
https://github.com/SunriseDigital/cs-sdx/pull/29

**Comment by gomo** [comment]
> Updateクラスの作成。Connectionに実行メソッド作成。

http://m97087yh.seesaa.net/article/262404575.html

http://sqlazure.jp/r/sql-server/403/

http://oracle.se-free.com/dml/09_select_update.html

UPDATEのサブクエリーは結構皆自由な実装をしていてクラスで吸収するの面倒ですね。使用頻度から考えて単純なものだけをConnectionに実装するのが吉かもしれん。

**Comment by gomo** [comment]
> UpdateのWhereはUpdateの対象テーブルで固定されているが、問題ないか検討。
>  Deleteクラスの作成。Connectionに実行メソッド作成。

この2点プラス

> UPDATEのサブクエリーは結構皆自由な実装をしていてクラスで吸収するの面倒ですね。使用頻度から考えて単純なものだけをConnectionに実装するのが吉かもしれん。

この辺をどうするか決め、[このコミット](https://github.com/SunriseDigital/cs-sdx/commit/d80283a8e1357596c57263f3a566d2d3910fd154)で実装しました。

Select/Update/Insert/Deleteは全てSQLなのでそれを組み立てるBulder的な抽象クラスがあってもいいと思い、実装しました。

**Comment by gomo** [comment]
> Contextのメソッドを整理。また、各具象クラスでサポートしないメソッドに関しては基本BuilderにProtectedで持って行って、各具象クラスでメソッドを作らないのがいいかも。

この点ついて詳細をメモしておく。
- Context内からAddColumnやWhere.Addを呼ぶとテーブル名を付与する機能があるが基本的にColumnやWhere句はBuilderが管理していてそちらに委譲する。
- 各builderの具象クラスによってサポートしないメソッドがあるがAddColumnValueなどはカラム名にテーブル名を付与する機能を使いたいのでContextから呼ぶ必要があり、Builderから呼べないとダメ。
- FluentSyntaxを使いたいので、AddColumnなどのpublicメソッドは各具象クラスの型で返す必要があるため、実装自体は親クラスに持って行っていいものでも持っていけない。型に厳しい言語特有の問題。

つまり、AddColumn系・AddColumnValue系などはBuilderと各具象クラス両方にないとダメということになる。同じ名前（つまりオーバーライド）にすると返す型も同じにしないとダメなのでなにか命名規則を考えるか、new就職しで親クラスのメソッドを隠せばもしかしたら行けるかもしれない。new修飾子は同じメソッドなのに代入された変数の型によって動作が変わる可能性があるので、ややこしいことになるのでやめたほうが良いかもしれないが・・・検討してみる。

**Comment by gomo** [comment]
> この点ついて詳細をメモしておく。

色々やっていて、だんだん固まってきた。
- builder以外を返すメソッドは、すべての実装、全ての公開メソッドを全部builderに持って行って、各具象クラスでサポートしてないものをオーバーライドして例外を投げる。Contextは具象クラスなので動的に呼び分けることができないのでBuilderにある必要がある。
- builderを返す物は実装のみBuilderに置いて、公開メソッドは各具象クラスに置く。サポートしないものもちゃんと作って、例外を投げるようにする。。

**Comment by gomo** [comment]
> 色々やっていて、だんだん固まってきた。

ふと思っったんだけど、全部Builderに持って行って、CreateSelectなんかの返り値の型もFetch系メソッドが受け取る型も全てbuilderにしてしまったらどうなんだろう。

FetchRecordなんかはSelectしか意味がなくUpdateやInsertをわたしても意味が無いというか、実行はされるけど、返り値の組み立てて例外になるのが気持ち悪いがDbCommandなんてまさにそんな扱いですよね。そもそもSqlがそういうもんだろって感じがする（つまり、SELECT文もUPDATE文もDBに投げたら実行されてるが、もし間違えて投げたら期待したのと違う結果になる）。

試しにやってみます。大変そうな変更だけど、どこをなせばいいか、コンパイル時に教えてくれるので、こういう変更をやる気になりますね。

## TODO
- [x] SetCommentは全具象クラスで可能にする。
- [x] `_`付きのメソッドは整理できそうなので確認。
- [x] コンストラクはbuilderに移動。
- [x] SelectのBuildをStringBuilderを使うように変更。
- [x] Condition.BuildもStringBuilderを使うように変更
- [x] Condition.BuildConditionString()もStringBuilderで置き換え。
- [x] Select.BuildColumsStringはBuilderに移動できないか？
- [x] 各具象クラスでサポートしてないメソッドは例外に。
- [x] Builder.ValueListが順番がずれるとエラーになりそうな問題を修正する
- [x] ContextにInsertとDeleteのプロパティ作成。
- [x] Contextのメソッドを整理。また、合わせて各具象クラスでサポートしないメソッドに関しては基本BuilderにProtectedで持って行って、各具象クラスでメソッドを作らないのがいいかも。
- [x] Builderに持っていけるものがないかもう一度確認

**Comment by gomo** [comment]
> Condition.BuildもStringBuilderを使うように変更

一旦作業したけど、Selectのテストとってからの方がいいので戻す

``` c#
    internal void Build(StringBuilder builder, Adapter adapter, DbParameterCollection parameters, Counter condCount)
    {
      if (this.EnableBracket)
      {
        builder.Append("(");
      }

      var first = true;
      wheres.ForEach(holder =>
      {
        if(!first)
        {
          builder.Append(holder.Logical.SqlString());
          first = false;
        }

        if (holder.Value is Condition)
        {
          Condition where = holder.Value as Condition;
          where.Build(builder, adapter, parameters, condCount);
        }
        else
        {
          builder.Append(this.BuildConditionString(adapter, parameters, holder, condCount));
        }
      });

      if (this.EnableBracket)
      {
        builder.Append(")");
      }
    }
```

**Comment by gomo** [comment]
とりあえず予定通り実装していみた。すっきりしたと思うが、Builderの具象クラスでサポートしてないメソッドは例外で実行時にエラーになる。せっかく型に厳しい言語なのにコンパイル時にエラーを出せなくなったのが残念。

共通部分を別クラスにして、委譲する方法も考えたが、Contextを取得しそのWhereにAddするとテーブル名を付与する機能は直感的で扱いやすいのがPHPのBuilderで経験済みなのでその機能は実現したい。Context内の型は抽象クラスにした方がいいので、今の形以外はどうしようも無さそう。

他にもこんなことを考えてみた。
- それぞれの具象クラスを状況に応じて生成し使い分けるシチュエーションは無さそうなので、間違えて渡してしまう確率は低いと思う。
- サポートする、しないが、DBのベンダーに依存しているのでAdapterを抽象クラスで扱う以上、動的に判断しないと行けない場合もある。
- カラム名やテーブル名などデータの持ち方がだいたい共通している。
- SQLにコメントを挿入する機能は全具象クラスで共通。

この部分の設計を変更するのはリリース後には厳しいので、今週末少し考えてみます。

**Comment by gomo** [comment]
> この部分の設計を変更するのはリリース後には厳しいので、今週末少し考えてみます。
> 
> 共通部分を別クラスにして、委譲する方法も考えたが、Contextを取得しそのWhereにAddするとテーブル名を付与する機能は直感的で扱いやすいのがPHPのBuilderで経験済みなのでその機能は実現したい。Context内の型は抽象クラスにした方がいいので、今の形以外はどうしようも無さそう。

Contextもそれぞれ、ContextSelect/ContextSelectなど別クラスにすればいけそうな気がする。どのくらい大変かちょっと眺めてみる。

**Comment by gomo** [comment]
> Contextもそれぞれ、ContextSelect/ContextSelectなど別クラスにすればいけそうな気がする。どのくらい大変かちょっと眺めてみる。

Builderを委譲にするのは割と簡単でした。
https://github.com/SunriseDigital/cs-sdx/pull/36

ただ、Contextも同じように、サポートしてないメソッドを呼べてしまうのでどうにかする必要がある。またWhereなどがContextを保持しているのでそこも各具象クラスを返すようジェネリックを導入する必要がありそう。かなり大幅な変更になるので時間がかかる。

もう一度問題を整理してみた
- Select/Update/Insert/Deleteは幾つかの処理が共通しているので使いまわしたい。
- Builderクラスを継承する形にしてみたが、単一責任の原則とリスコフの置換原則に違反しているのであまり良い設計ではない。
- Builderクラスを以上する形に変更してみたが、Contextは共有してしまうので、ContextもSelect用など各クラスを作らなければならない。

整理してみて思ったのですが、スタート地点の

> Select/Update/Insert/Deleteは幾つかの処理が共通しているので使いまわしたい。

がいかんかったような気がしてきました。Update/Insert/Deleteはそれほど複雑な処理が必要ではないと思うので、インターフェースは揃えてもいいけど、処理は独自実装すればよいのでは、と思い始めた。ブランチそのままにして、一旦巻き戻して眺めて見ます。
- [x] UpdateのWhereはテーブル名を付与しないように実装。
- [x] Deleteの実装。
- [x] SelectはStringBuilderを使うように。
- [x] FetchLastInsertIdの返り値の問題を再修正。
- [x] SelectのコンストラクタはAdapter固定にする。

**Comment by gomo** [comment]
https://github.com/SunriseDigital/cs-sdx/pull/37#issuecomment-146072107
ということです。

**Comment by gomo** [comment]
https://github.com/SunriseDigital/cs-sdx/commit/666bfa2c96e386c2ccc00d208f59e4c60c248c74
マージしたので閉じます。
